inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
    - Policyfile.rb
  Exclude:
    - vendor/**/*
    - chef-zero-local/**/*

AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
LineLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
